# # PostgreSQL. Versions 9.1 and up are supported.
# #
# # Install the pg driver:
# #   gem install pg
# # On OS X with Homebrew:
# #   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# # On OS X with MacPorts:
# #   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# # On Windows:
# #   gem install pg
# #       Choose the win32 build.
# #       Install PostgreSQL and put its /bin directory on your path.
# #
# # Configure Using Gemfile
# # gem 'pg'
# #
# default: &default
#   adapter: postgresql
#   encoding: unicode
#   # For details on connection pooling, see Rails configuration guide
#   # http://guides.rubyonrails.org/configuring.html#database-pooling
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

# development:
#   <<: *default
#   database: lead_retail_development

#   # The specified database role being used to connect to postgres.
#   # To create additional roles in postgres see `$ createuser --help`.
#   # When left blank, postgres will use the default role. This is
#   # the same name as the operating system user that initialized the database.
#   #username: lead_retail

#   # The password associated with the postgres role (username).
#   #password:

#   # Connect on a TCP socket. Omitted by default since the client uses a
#   # domain socket that doesn't need configuration. Windows does not have
#   # domain sockets, so uncomment these lines.
#   #host: localhost

#   # The TCP port the server listens on. Defaults to 5432.
#   # If your server runs on a different port number, change accordingly.
#   #port: 5432

#   # Schema search path. The server defaults to $user,public
#   #schema_search_path: myapp,sharedapp,public

#   # Minimum log levels, in increasing order:
#   #   debug5, debug4, debug3, debug2, debug1,
#   #   log, notice, warning, error, fatal, and panic
#   # Defaults to warning.
#   #min_messages: notice

# # Warning: The database defined as "test" will be erased and
# # re-generated from your development database when you run "rake".
# # Do not set this db to the same as development or production.
# test:
#   <<: *default
#   database: lead_retail_test

# # As with config/secrets.yml, you never want to store sensitive information,
# # like your database password, in your source code. If your source code is
# # ever seen by anyone, they now have access to your database.
# #
# # Instead, provide the password as a unix environment variable when you boot
# # the app. Read http://guides.rubyonrails.org/configuring.html#configuring-a-database
# # for a full rundown on how to provide these environment variables in a
# # production deployment.
# #
# # On Heroku and other platform providers, you may have a full connection URL
# # available as an environment variable. For example:
# #
# #   DATABASE_URL="postgres://myuser:mypass@localhost/somedatabase"
# #
# # You can use this database configuration with:
# #
# #   production:
# #     url: <%= ENV['DATABASE_URL'] %>
# #
production:
  primary:
    adapter: postgresql
    encoding: unicode
    url: <%= ENV['DATABASE_URL'] %>
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 60 } %>
  follower_replica:
    adapter: postgresql
    encoding: unicode
    url: <%= ENV['DATABASE_URL_FOLLOWER'] %>
    replica: true
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 60 } %>

# development:
#   adapter: postgresql
#   host: ec2-63-33-150-229.eu-west-1.compute.amazonaws.com
#   username: u6621ckc78114l
#   password: pef961af3fa38f6fd9033f50141e3701c3d22f946c98c723605959957aeed3e88
#   database: dbt1a3k0a50pe0
#   encoding: UTF8

development:
  primary:
    adapter: postgresql
    url: postgres://postgres:Syedtosh@database-1.csg12djtu7vv.us-east-1.rds.amazonaws.com:5432/demomigrate
    # url: postgres://u56kreej2db4o:p3a0211f581fe197a4c1274eb85ec737013bfc8a67e5774d11a898653bb768173@ec2-52-48-46-187.eu-west-1.compute.amazonaws.com:5432/dbt1a3k0a50pe0
    # url: postgres://u6d7puu8ph6gji:p8fca2877f3e46a2c2df0df4091cbdbb911992d3689afff00ffcaa2c5bd3ee695@ec2-54-171-5-26.eu-west-1.compute.amazonaws.com:5432/deivu27qv0jjh0
    # url: postgres://uf98ohlrd468a1:p271457f62acb7d21e70847a09046396ed7f41d76a98bd4fcfc179986f661ca85@ec2-54-73-220-105.eu-west-1.compute.amazonaws.com:5432/d47iq60lkcr01e
    # host: ec2-54-72-133-225.eu-west-1.compute.amazonaws.com
    # username: u90uhss1g6jfq5
    # password: pa5d78d1945c5e33f19dd45a28b9379cc78e82ba26c3af5d49407b967db07cff2
    # database: deln1rp7aqcofr
    encoding: unicode
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  follower_replica:
    adapter: postgresql
    url: postgres://postgres:Syedtosh@database-1.csg12djtu7vv.us-east-1.rds.amazonaws.com:5432/demomigrate
    
    # url: postgres://u56kreej2db4o:p3a0211f581fe197a4c1274eb85ec737013bfc8a67e5774d11a898653bb768173@ec2-52-48-46-187.eu-west-1.compute.amazonaws.com:5432/dbt1a3k0a50pe0
    # url: postgres://u6d7puu8ph6gji:p8fca2877f3e46a2c2df0df4091cbdbb911992d3689afff00ffcaa2c5bd3ee695@ec2-54-228-110-159.eu-west-1.compute.amazonaws.com:5432/deivu27qv0jjh0
    # url: postgres://uf98ohlrd468a1:p271457f62acb7d21e70847a09046396ed7f41d76a98bd4fcfc179986f661ca85@ec2-34-250-254-72.eu-west-1.compute.amazonaws.com:5432/d47iq60lkcr01e
    # host: ec2-54-72-91-5.eu-west-1.compute.amazonaws.com
    # username: u90uhss1g6jfq5
    # password: pa5d78d1945c5e33f19dd45a28b9379cc78e82ba26c3af5d49407b967db07cff2
    # database: deln1rp7aqcofr
    encoding: unicode
    replica: true
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
